version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - hiveserver-network
  hive-server:
    hostname: hive-server
    build: .
    ports:
      - '10000:10000' # Port for Beeline
    volumes:
      - ${PWD}/hivedata:/user/hive
      - ${PWD}/conf/hive-site.xml:/opt/apache-hive-3.1.3-bin/conf/hive-site.xml
      - ${PWD}/conf/hive-log4j2.properties:/opt/apache-hive-3.1.3-bin/conf/hive-log4j2.properties
      - ${PWD}/conf/core-site.xml:/opt/hadoop-3.3.3/etc/hadoop/core-site.xml
    depends_on:
      - mariadb
    networks:
      - hiveserver-network
  minio:
    hostname: minio
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - hiveserver-network
      
networks:
  hiveserver-network:
    driver: bridge
